name: Linter
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest go version
        id: version
        run: |
          echo "::set-output name=value::$(curl 'https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json' --silent | jq '.[0].version' -r)"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.value }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
