name: Release
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get latest go version
      #  uses: sergeysova/jq-action@v2.1.0
      #  id: version
      #  with:
      #    cmd: curl "https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json" --silent | jq '.[0].version' -r

        id: version
        run: |
          cd $env:SystemRoot/system32 && curl -L -O https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
          $output=$(curl "https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json" --silent | jq-win64 '.[0].version' -r)
          echo "::set-output name=value::$output"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.value }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies, run test
        run: |
          go test ./...

      - name: Build
        env:
          NAME: clash
          BINDIR: bin
        run: |
          make build_dep
          make -j releases

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/releases/*
          draft: false
